# Generated by Django 6.0.2 on 2026-03-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_waitlist_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_required',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email for unauthenticated guests', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('payment_pending', 'Ожидает предоплаты'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('cancelled_by_user', 'Отменено пользователем'), ('cancelled_by_restaurant', 'Отменено рестораном'), ('expired', 'Истекло'), ('completed', 'Завершено'), ('no_show', 'Неявка')], default='pending', max_length=30),
        ),
    ]
