# Generated by Django 6.0.3 on 2026-03-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_extend_reservationhistory_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('payment_pending', 'Ожидает предоплаты'), ('approved', 'Подтверждено'), ('seated', 'Гость за столом'), ('rejected', 'Отклонено'), ('cancelled_by_user', 'Отменено пользователем'), ('cancelled_by_restaurant', 'Отменено рестораном'), ('expired', 'Истекло'), ('completed', 'Завершено'), ('no_show', 'Неявка')], default='pending', max_length=30),
        ),
    ]
