# Generated by Django 6.0.3 on 2026-03-23 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_add_seated_status'),
        ('restaurants', '0022_table_fix_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking_per_slot',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('payment_pending', 'Ожидает предоплаты'), ('confirmed', 'Подтверждено'), ('seated', 'Гость за столом'), ('rejected', 'Отклонено'), ('cancelled_by_user', 'Отменено пользователем'), ('cancelled_by_restaurant', 'Отменено рестораном'), ('expired', 'Истекло'), ('completed', 'Завершено'), ('no_show', 'Неявка')], default='pending', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('user', 'restaurant', 'date', 'time'), name='unique_active_booking_per_slot'),
        ),
    ]
