# Generated by Django 6.0.3 on 2026-03-25 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_remove_booking_source'),
        ('restaurants', '0025_table_table_seats_gte_1_table_table_seats_lte_20_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__lte', 480)), name='booking_duration_max_480'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('guests__lte', 20)), name='booking_guests_lte_20'),
        ),
    ]
