# Generated by Django 6.0.3 on 2026-03-31 15:46

import uuid

import bookings.models
from django.db import migrations, models


def backfill_booking_public_tokens(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    for booking in Booking.objects.filter(public_token__isnull=True).only('id'):
        booking.public_token = uuid.uuid4().hex
        booking.save(update_fields=['public_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_remove_booking_unique_active_booking_per_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='public_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.RunPython(backfill_booking_public_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='booking',
            name='public_token',
            field=models.CharField(db_index=True, default=bookings.models.generate_booking_public_token, editable=False, max_length=32, unique=True),
        ),
    ]
