# Generated by Django 6.0.3 on 2026-03-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_restaurant_deposit_amount_per_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], default='starter', max_length=20),
        ),
    ]
