# Generated by Django 6.0.3 on 2026-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_table_name_capacity_optional_xy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Max guests (1–20)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='height',
            field=models.FloatField(default=60.0),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(help_text="Table name/label, e.g. '1', 'A1', 'VIP-1'", max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='rotation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='table',
            name='width',
            field=models.FloatField(default=60.0),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'name')},
        ),
    ]
