# Generated by Django 6.0.3 on 2026-03-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_table_name_capacity_primary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(help_text="Table label, e.g. '1', 'A1', 'VIP-1'", max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(help_text='Max guests (1–20)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='x',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='y',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'number')},
        ),
    ]
