# Generated by Django 6.0.3 on 2026-03-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_table_fix_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bot_token',
            field=models.CharField(blank=True, help_text='Telegram Bot token from @BotFather. Each restaurant has its own bot.', max_length=200, null=True, unique=True),
        ),
    ]
