# Generated by ChatGPT on 2026-03-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0023_add_bot_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="bot_token",
        ),
    ]

