# Generated by Django 6.0.3 on 2026-03-27 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_table_table_seats_gte_1_table_table_seats_lte_20_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='birthday_service_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_kids_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_namazhana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_terrace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_party_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='turnover_default_min',
            field=models.PositiveIntegerField(default=85),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='grid_h',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='table',
            name='grid_w',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='table',
            name='grid_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='grid_y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('days_of_week', models.JSONField(default=list)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('grid_cols', models.PositiveIntegerField(default=8)),
                ('grid_rows', models.PositiveIntegerField(default=6)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='restaurants.zone'),
        ),
    ]
