# Generated by Django 6.0.3 on 2026-04-02 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0027_restaurant_subscription_plan_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='current_period_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='current_period_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payment_status',
            field=models.CharField(choices=[('inactive', 'Не активна'), ('trial', 'Тестовый период'), ('active', 'Активна'), ('grace', 'Льготный период'), ('past_due', 'Просрочена'), ('canceled', 'Отменена')], default='inactive', max_length=20),
        ),
        migrations.CreateModel(
            name='RestaurantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('target_type', models.CharField(default='restaurant', max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', '-created_at'], name='restaurants_restaur_ef5cf1_idx'), models.Index(fields=['event_type', '-created_at'], name='restaurants_event_t_0a50e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('none', 'Без подписки'), ('plus', 'Plus'), ('pro', 'Pro')], max_length=20)),
                ('number', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KZT', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Не оплачен'), ('void', 'Аннулирован')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['restaurant', '-issued_at'], name='restaurants_restaur_cab4dc_idx'), models.Index(fields=['restaurant', 'status'], name='restaurants_restaur_e83e31_idx')],
            },
        ),
    ]
