# Generated by Django 6.0.3 on 2026-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_marketing_automations_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationlog',
            name='type',
            field=models.CharField(choices=[('reminder', 'Reminder (2 hours before)'), ('thank_you', 'Thank You (After Visit)'), ('inactivity', 'Inactivity (30 days)'), ('birthday', 'Birthday (7 days before)'), ('win_back', 'Win Back (30 days since last visit)'), ('review_request', 'Review Request (2 hours after visit)'), ('no_show_followup', 'No‑show follow-up')], max_length=32),
        ),
    ]
