# Generated by Django 6.0.2 on 2026-03-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_remove_booking_booking_duration_gte_1_and_more'),
        ('chat', '0001_initial'),
        ('restaurants', '0017_restaurantrequest_restaurants_status_411a0a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='message',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.booking'),
        ),
    ]
