# Generated by Django 6.0.3 on 2026-03-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_marketing_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags like VIP, influencer, family, etc.', max_length=255),
        ),
    ]
