# Generated by Django 6.0.3 on 2026-03-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='flag',
            field=models.CharField(blank=True, choices=[('vip', 'VIP'), ('problem', 'Problem'), ('new', 'New'), ('regular', 'Regular')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_show_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
