# Generated by Django 6.0.3 on 2026-03-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('global_admin', 'Глобальный Админ'), ('owner', 'Владелец'), ('manager', 'Менеджер'), ('host', 'Хостес'), ('customer', 'Гость'), ('pending', 'Ожидает выбора роли')], default='customer', max_length=20),
        ),
    ]
